version: '2'

services: 
    condaJupy:
        image: ofirkedem/jupyter-conda-karnel:0.0
        ports: 
            - 8888:8888
        volumes:
            - ${PWD}/notebooks:/home/jovyan/notebooks
